### ISSUE TITLE
yarn berry Error: create-jest-runner tried to access jest-runner (a peer dependency) but it isn't provided by its ancestors

### ISSUE THREAD

**Issue by xenoterracide** [jest-community/jest-runner-tsd#97]
```
❯ yarn jest
Error: create-jest-runner tried to access jest-runner (a peer dependency) but it isn't provided by its ancestors; this makes the require call ambiguous and unsound.

Required package: jest-runner
Required by: create-jest-runner@virtual:f3a1aa84056e0c9bae1641138e71f4a6777a2cdf049b6d742bae451fc08717f5ce327e91580a4167fe0dec92b44f1ee97b8bd064f0aeb1afd7237b152c12efab#npm:0.11.1 (via /Users/nqy642/IdeaProjects/E1-Library/.yarn/__virtual__/create-jest-runner-virtual-108a2314ea/0/cache/create-jest-runner-npm-0.11.1-8026afed73-6fc69d9fe3.zip/node_modules/create-jest-runner/build/)

Ancestor breaking the chain: jest-runner-tsd@virtual:d97b79db4fda8f479e265452a16c3344f5cce9cf2b369c79cb7dd5d8f9a8b5dca20c35b42ad804c2caebb36e7ad1004e4131c47d5d929fa5fbba7a20044f5ecf#npm:3.1.0


Require stack:
- /Users/nqy642/IdeaProjects/E1-Library/.yarn/__virtual__/create-jest-runner-virtual-108a2314ea/0/cache/create-jest-runner-npm-0.11.1-8026afed73-6fc69d9fe3.zip/node_modules/create-jest-runner/build/createJestRunner.js
- /Users/nqy642/IdeaProjects/E1-Library/.yarn/__virtual__/create-jest-runner-virtual-108a2314ea/0/cache/create-jest-runner-npm-0.11.1-8026afed73-6fc69d9fe3.zip/node_modules/create-jest-runner/build/index.js
- /Users/nqy642/IdeaProjects/E1-Library/.yarn/__virtual__/jest-runner-tsd-virtual-f3a1aa8405/0/cache/jest-runner-tsd-npm-3.1.0-d9ef8343c8-c080b642ca.zip/node_modules/jest-runner-tsd/src/index.js
- /Users/nqy642/IdeaProjects/E1-Library/.yarn/cache/jest-util-npm-28.1.3-9ae2283a08-fd6459742c.zip/node_modules/jest-util/build/requireOrImportModule.js
- /Users/nqy642/IdeaProjects/E1-Library/.yarn/cache/jest-util-npm-28.1.3-9ae2283a08-fd6459742c.zip/node_modules/jest-util/build/index.js
- /Users/nqy642/IdeaProjects/E1-Library/.yarn/__virtual__/jest-config-virtual-fb81c2f38c/0/cache/jest-config-npm-28.1.3-47d1c91477-ddabffd3a3.zip/node_modules/jest-config/build/getCacheDirectory.js
- /Users/nqy642/IdeaProjects/E1-Library/.yarn/__virtual__/jest-config-virtual-fb81c2f38c/0/cache/jest-config-npm-28.1.3-47d1c91477-ddabffd3a3.zip/node_modules/jest-config/build/Defaults.js
- /Users/nqy642/IdeaProjects/E1-Library/.yarn/__virtual__/jest-config-virtual-fb81c2f38c/0/cache/jest-config-npm-28.1.3-47d1c91477-ddabffd3a3.zip/node_modules/jest-config/build/normalize.js
- /Users/nqy642/IdeaProjects/E1-Library/.yarn/__virtual__/jest-config-virtual-fb81c2f38c/0/cache/jest-config-npm-28.1.3-47d1c91477-ddabffd3a3.zip/node_modules/jest-config/build/index.js
- /Users/nqy642/IdeaProjects/E1-Library/.yarn/__virtual__/jest-cli-virtual-5919ff1e13/0/cache/jest-cli-npm-28.1.3-aab5c7389d-fb424576bf.zip/node_modules/jest-cli/build/init/index.js
- /Users/nqy642/IdeaProjects/E1-Library/.yarn/__virtual__/jest-cli-virtual-5919ff1e13/0/cache/jest-cli-npm-28.1.3-aab5c7389d-fb424576bf.zip/node_modules/jest-cli/build/cli/index.js
- /Users/nqy642/IdeaProjects/E1-Library/.yarn/__virtual__/jest-cli-virtual-5919ff1e13/0/cache/jest-cli-npm-28.1.3-aab5c7389d-fb424576bf.zip/node_modules/jest-cli/build/index.js
- /Users/nqy642/IdeaProjects/E1-Library/.yarn/__virtual__/jest-cli-virtual-5919ff1e13/0/cache/jest-cli-npm-28.1.3-aab5c7389d-fb424576bf.zip/node_modules/jest-cli/bin/jest.js
- /Users/nqy642/IdeaProjects/E1-Library/.yarn/__virtual__/jest-virtual-65092f3388/0/cache/jest-npm-28.1.3-207c50e059-b9dcb542eb.zip/node_modules/jest/bin/jest.js
    at Function.require$$0.Module._resolveFilename (/Users/nqy642/IdeaProjects/E1-Library/.pnp.cjs:17439:13)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/Users/nqy642/IdeaProjects/E1-Library/.yarn/cache/@cspotcode-source-map-support-npm-0.8.1-964f2de99d-5718f26708.zip/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at Function.require$$0.Module._load (/Users/nqy642/IdeaProjects/E1-Library/.pnp.cjs:17293:42)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/nqy642/IdeaProjects/E1-Library/.yarn/__virtual__/create-jest-runner-virtual-108a2314ea/0/cache/create-jest-runner-npm-0.11.1-8026afed73-6fc69d9fe3.zip/node_modules/create-jest-runner/build/createJestRunner.js:8:19)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at require$$0.Module._extensions..js (/Users/nqy642/IdeaProjects/E1-Library/.pnp.cjs:17483:33)
    at require.extensions.<computed> (/Users/nqy642/IdeaProjects/E1-Library/.yarn/__virtual__/ts-node-virtual-57b3eea5c8/0/cache/ts-node-npm-10.9.1-6c268be7f4-090adff130.zip/node_modules/ts-node/src/index.ts:1608:43)
```

I suspect this is an issue with support for yarn and how it's doing its require/and or lack of a dependency on jest? or something?

```ts
import { InitialOptionsTsJest } from 'ts-jest'
import { defaults as tsjPreset } from 'ts-jest/presets'

const config: InitialOptionsTsJest = {
  testEnvironment: 'node',
  preset: 'ts-jest',
  testPathIgnorePatterns: ['/(\\.test|node_modules|dist)'],
  projects: [
    {
      displayName: 'unit',
      testMatch: ['<rootDir>/**/test/unit/**/*.test.ts'],
      runner: 'jest-runner',
      transform: { ...tsjPreset.transform },
    },
    {
      displayName: 'types',
      runner: 'jest-runner-tsd',
      testMatch: ['<rootDir>/**/test/types/**/*.test.ts'],
    },
  ],
  // setupFilesAfterEnv: ['jest-extended/all'],
}
export default config
```

```ts
import { createErrorCodes } from '@cof/e1-types'
import { describe, test } from '@jest/globals'
import Joi from 'joi'
import { expectType } from 'tsd-lite'

import { validateRequired } from '../../src/validate'

describe('validate', () => {
  const errorCodes = createErrorCodes({
    limit: [100023],
    npe: [200099, ''],
  } as const)
  describe('validateRequired', () => {
    test('string', () => {
      const arg = 'v'

      expectType<string>(validateRequired(arg, Joi.any(), 'npe'))
    })
  })
})
```

## System:
 - OS: macOS 11.6.8
 - CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
## Binaries:
 - Node: 16.14.2 - /private/var/folders/xk/s3n8ww014pzbx2sn30ctz7000000gq/T/xfs-cda192a6/node
 - Yarn: 3.2.2 - /private/var/folders/xk/s3n8ww014pzbx2sn30ctz7000000gq/T/xfs-cda192a6/yarn
 - npm: 8.5.0 - ~/.asdf/plugins/nodejs/shims/npm

```
❯ yarn why jest-runner-tsd && yarn why  @tsd/typescript && yarn why tsd-lite
└─ @cof/e1-lib@workspace:.
   └─ jest-runner-tsd@npm:3.1.0 [d97b7] (via npm:^3.1.0 [d97b7])
├─ @cof/e1-lib@workspace:.
│  └─ @tsd/typescript@npm:4.7.4 (via npm:^4.7.4)
│
├─ @cof/e1-types@workspace:packages/types
│  └─ @tsd/typescript@npm:4.7.4 (via npm:^4.7.4)
│
└─ @cof/e1-util@workspace:packages/util
   └─ @tsd/typescript@npm:4.7.4 (via npm:^4.7.4)
├─ @cof/e1-types@workspace:packages/types
│  └─ tsd-lite@npm:0.5.6 [f3a1a] (via npm:^0.5.4 [f3a1a])
│
├─ @cof/e1-util@workspace:packages/util
│  └─ tsd-lite@npm:0.5.6 [f3a1a] (via npm:^0.5.4 [f3a1a])
│
├─ jest-runner-tsd@npm:3.1.0
│  └─ tsd-lite@npm:0.5.6 (via npm:^0.5.4)
│
└─ jest-runner-tsd@npm:3.1.0 [d97b7]
   └─ tsd-lite@npm:0.5.6 [f3a1a] (via npm:^0.5.4 [f3a1a])
```

**Comment by SimenB** [comment]
https://github.com/jest-community/create-jest-runner/releases/tag/v0.11.2

**Comment by SimenB** [comment]
And https://github.com/jest-community/jest-runner-tsd/releases/tag/v3.1.1 to force it 🙂
